#include "levels.h"

const Key levels[LEVELS_COUNT] = {
    KEY_RED,
    KEY_BLUE,
    KEY_YELLOW,
    KEY_GREEN,
    KEY_BLUE,
    KEY_GREEN,
    KEY_YELLOW,
    KEY_RED,
    KEY_RED,
    KEY_BLUE,
    KEY_GREEN,
    KEY_YELLOW,
    KEY_YELLOW,
    KEY_RED,
    KEY_BLUE,
    KEY_GREEN,
    KEY_BLUE,
    KEY_RED,
    KEY_GREEN,
    KEY_YELLOW,
    KEY_RED,
    KEY_BLUE,
    KEY_GREEN,
    KEY_YELLOW,
    KEY_GREEN,
    KEY_BLUE,
    KEY_YELLOW,
    KEY_RED,
    KEY_GREEN,
    KEY_BLUE
};
